### ISSUE TITLE
Uninitialized CameraController, startImageStream was called on uninitialized CameraController

### ISSUE THREAD

**Issue by RakhimyanTim** [am15h/object_detection_flutter#2]
Hi @am15h Thanks for your job! 
I was able to test your app and find out some error - Uninitialized CameraController. Can you explain to me what is wrong? 
Thanks!

**Comment by am15h** [comment]
Hi @RakhimyanTim, Sorry I missed this. Can you elaborate a little more? Are you using the exact same code from this repository or any modifications have been made?

**Comment by RakhimyanTim** [comment]
I'm using the same code from your repository.. without any modifications..

**Comment by sahalshajim** [comment]
I was able to solve this issue by initializing camera before calling main function like this :
==================
List<CameraDescription> cameras;
Future<Null> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    cameras = await availableCameras();
  } on CameraException catch (e) {
    print('Error: $e.code\nError Message: $e.message');
  }
  runApp(new MyApp());
}
==================
Pass the cameras list to Home View and then to Camera View and use it there instead of the initializing cameras in Camera View Page which causes the error

**Comment by bqubique** [comment]
For anyone still dealing with an issue like this one, checking whether the CameraController was initialised helped me 🙃.
```
if(cameraController.value.isInitialized){
    //do stuff with cameraController here
}
```
P.S. My issue was not related to this package, but rather it was related to processing camera stream for pose detection.
